---
- hosts: RHEL
  tasks:
  - name: Ping test
    ansible.builtin.ping:
  - name: installing podman
    package:
      name: "podman"
      state: present
  - name: Pull an image
    containers.podman.podman_image:
      name: httpd
  - name: Copying file into home
    copy:
      src: /root/ws1/index.html
      dest: /home
  - name: Re-create a redis container
    containers.podman.podman_container:
      name: sarthak
      image: httpd
      state: started
      detach: true
      exposed_ports:
        - 80
      ports:
        - 4444:80
      volumes: /home/:/usr/local/apache2/htdocs/